name: remittance_mobile
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  aws_s3_upload_lite:
    git:
      url: https://github.com/maraz-dev/aws_s3_upload_lite.git
  camera: ^0.11.0+1
  clock: ^1.1.1
  config:
    path: config
  cupertino_icons: ^1.0.6
  curl_logger_dio_interceptor: ^1.0.0
  device_info_plus: ^10.1.0
  dio: ^5.4.0
  dio_cache_interceptor: ^3.4.3
  dio_cache_interceptor_hive_store: ^3.2.1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  event_bus: ^2.0.1
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_skeleton_ui: ^0.0.6
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  geocoding: ^3.0.0
  geolocator: any
  get_ip_address: ^0.0.7
  get_it: ^7.2.0
  go_router: ^13.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.9
  http: ^1.2.2
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  local_auth: ^2.2.0
  local_auth_android: ^1.0.38
  local_auth_darwin: ^1.3.1
  logging: ^1.2.0
  number_text_input_formatter: ^1.0.0+8
  path_provider: ^2.1.3
  pdf: ^3.11.1
  pinput: ^3.0.1
  pretty_dio_logger: ^1.1.1
  screenshot: ^3.0.0
  share_plus: ^10.1.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  timelines: ^0.1.0
  uuid: ^4.5.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  ios: true
  android: true
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/images/country/
    - assets/fonts/
    - assets/countries.json
    - .env

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/Regular.otf
        - asset: assets/fonts/Bold.otf
        - asset: assets/fonts/Bold.otf
          weight: 500
        - asset: assets/fonts/Medium.otf
